services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - /var/www/express_app/src:/app/src

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: express_app
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: